repos:
  # --- Импорт и сортировка ---
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
  # --- Автоформатирование кода ---
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  # --- Проверка стиля и ошибок ---
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8

  # --- Проверка типов ---
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [
          "--install-types",
          "--non-interactive",
          "--explicit-package-bases",
          "--ignore-missing-imports" # Поможет, если какой-то либы нет в типах
        ]
          # Убираем types-all, оставляем только базу
        additional_dependencies: [
          "types-setuptools",
          "types-requests", # пример, если используешь requests
          "tokenize-rt==5.2.0"
        ]

  # --- Локальный хук для тестов ---
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest tests
        language: system
        pass_filenames: false
